model_tab = tabPanel("Model Specification",
         h3("Model:"),
         uiOutput("modeltext"),
         selectInput(inputId = "model_selection_type",
                     label = "Model Selection Type",
                     choices = c("Linear Equation" = "lineareq",
                                 "Stressor Response Function(s)" = "stressor"),
                     selected = "lineareq"),
         uiOutput('model_selection_panel'),
         uiOutput('stress_response_figures'),
         #tags$div(id = 'variable_stressor_models'),
         #tags$div(id = "variable_coefs"),
         hr(),
         hr(),
         h3("Model Output"),
         dataTableOutput('model_result'),
)