model_tab = tabPanel("Model Specification",
         h3("Model:"),
         uiOutput("modeltext"),
         selectInput(inputId = "model_selection_type",
                     label = "Model Selection Type",
                     choices = c("Linear Equation" = "lineareq",
                                 "Sigmoidal Stressor" = "sigmoidal",
                                 "Hyperbolic Stressor" = "hyperbolic"),
                     selected = "lineareq"),
         uiOutput('model_selection_panel'),
         hr(),
         hr(),
         h3("Model Output"),
         dataTableOutput('model_result'),
)